### ISSUE TITLE
Website throws "Uncaught ReferenceError: $ is not defined"

### ISSUE THREAD

**Issue by trivikr** [bartaz/bartaz.github.com#2]
![Screen Shot 2019-11-14 at 12 39 58 PM](https://user-images.githubusercontent.com/16024985/68894326-f2d6f680-06db-11ea-98a3-dc82bc82ba2a.png)

**Comment by bartaz** [comment]
Oh, thanks. I haven't updated it in a loooong time. Seems some browsers started blocking unsecure link to jQuery.

I changed it to https, so should work once site is refreshed on GitHub Pages.

Thanks for report!
